logging:
  level:
    root: INFO
  time-rolling-file:
    file: '${app.base}/logs/${spring.application.name}.%d{yyyy-MM-dd}.log'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [${spring.application.name}] [%X{traceId}] [%thread] %-5level %logger %msg%n %ex{10}'
    time-rolling-file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [${spring.application.name}] [%X{traceId}] [%thread] %-5level %logger %msg%n %ex{10}'