# ----------------------------------------------------------------
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

# ----------------------------------------------------------------

logging:
  level:
    root: INFO
  time-rolling-file:
    file: '${app.home}/logs/${spring.application.name}.%d{yyyy-MM-dd}.log'
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %red([%X{traceId}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) %cyan(%msg%n) %ex{10}'